#!/bin/sh
fullname () {
  local myDIR=`dirname "$1"`
  local prev=`pwd`
  cd "$myDIR" >/dev/null
  realDIR=`pwd`
  cd "$prev" > /dev/null
  local basefile=`basename "$1"`
  echo "$realDIR/$basefile"
}

SCRIPT_NAME=`fullname $0`
echo "SCRIPT_NAME:$SCRIPT_NAME"
FGLPEDPATH=`dirname $SCRIPT_NAME` 
#we recompile everything always: hence avoid version clashes
make -C $FGLPEDPATH clean all > /dev/null
export FGLPEDPATH
export FGLRESOUREPATH=$FGLPEDPATH:$FGLRESOURPATH
export DBPATH=$FGLPEDPATH:$DBPATH
exec fglrun $FGLPEDPATH/fglped.42m "$@" 
